### ISSUE TITLE
Add countdown for teleportation

### ISSUE THREAD

**Issue by SuperAdam47** [unknownguy2002/pmmp-rtp#1]

**Comment by jamesrchen** [comment]
Will do, thanks for the suggestion!

**Comment by jamesrchen** [comment]
I added the feature, it would be awesome if you could test it for any bugs!

**Comment by jamesrchen** [comment]
Added in https://github.com/unknownguy2002/pmmp-rtp/commit/f6110e274c1fce6cebd59d8b8dc2c1abe26d472f

**Comment by SuperAdam47** [comment]
Dont use this code ```sleep(1);``` for countdown
sleep code  freezes server

**Comment by jamesrchen** [comment]
Oh, yes. How silly of me. I'll fix that right away, sorry. I forgot it isn't running asynchronously

**Comment by jamesrchen** [comment]
I fixed the problem with tasks, I hope. If you have time, I'd be grateful if you tested it. Thanks!

**Comment by jamesrchen** [comment]
https://github.com/unknownguy2002/pmmp-rtp/commit/370148b816f6d12051d6ea155c192cfeeb8a0af3
