### ISSUE TITLE
Upgrade plugin for Goodest

### ISSUE THREAD

**Issue by SuperAdam47** [unknownguy2002/pmmp-rtp#2]
- Add custom warps to random teleportation
- Add pvp protection after teleport

**Comment by jamesrchen** [comment]
Starting work on it later today.

**Comment by jamesrchen** [comment]
PVP protection is added with the invincibility.

**Comment by SuperAdam47** [comment]
... 1 year later

**Comment by SuperAdam47** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/16169771/64886169-36769b00-d66e-11e9-89d9-c7b51e336a1a.PNG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/16169771/64886325-90776080-d66e-11e9-8f2c-6ee06b50c5d5.PNG)
![Ekran Alıntısı3](https://user-images.githubusercontent.com/16169771/64886328-92412400-d66e-11e9-8dfd-f8b3fb4dade8.PNG)
![Ekran Alıntısı4](https://user-images.githubusercontent.com/16169771/64886329-940ae780-d66e-11e9-81cb-d7ee3fee0e8c.PNG)

**Comment by SuperAdam47** [comment]
... 2 year later

**Comment by jamesrchen** [comment]
I have, for the most part, abandoned this plugin as I am focusing on my academic studies. I hope you understand

**Comment by SuperAdam47** [comment]
I understand you, but this was something you could do in 10 minutes
